<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Netsol
 * @package     Netsol_Orderhistory
 * @copyright   Copyright (c) 2016 Netsolutions India (http://www.netsolutions.in)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

$productIds =  $this->predictiveAnalysisBlock();
$count = count($productIds);
$enabled = Mage::helper('orderhistory/data')->isEnabled();
$heading = Mage::helper('orderhistory/data')->getHeading();
?>
<?php if($enabled == 1){ ?>
<div class="predictive-analytic" id="vert-bx-slider">
	<?php if(Mage::getSingleton('customer/session')->isLoggedIn() || count($productIds)){?>
		<?php if(count($productIds)){
				if($heading == ""){
				?>
				<h4><?php echo $this->__('You may also be interested in the following recommended product(s)'); ?></h4>
		<?php }else { ?>
			<h4><?php echo $heading; ?></h4>
			<?php } ?>
				<div class="owl-carousel mini-products-list" id="owl-vert">
					<?php foreach($productIds as $productId):
							$product = Mage::getModel('catalog/product')->load($productId); 
					 ?>
					<div class="item">
						<a href="<?php echo $product->getProductUrl() ?>" title="<?php echo $this->escapeHtml($product->getName()) ?>" class="product-image">
							<img src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(150) ?>" alt="" />
						</a>
						<div class="product-details">
						<h3 class="product-name"><a href="<?php echo $product->getProductUrl() ?>" title="<?php echo $this->escapeHtml($product->getName()) ?>"><?php echo $product->getName(); ?></a></h3>
						<?php echo $this->getPriceHtml($product, true);?>
						</div>
					</div>
					   
				<?php endforeach; ?>
				</div>
			<?php }else{ ?>
			<?php } ?>
	<?php }else{?>
	<h4><?php echo $this->__('Please login to see recommended product.') ?></h4>
	<?php } ?>
</div>
<script type="text/javascript">
	jQuery.noConflict();
	jQuery(document).ready(function() {
		  jQuery("#owl-vert").owlCarousel({
			  autoPlay: 2000, 
			  items: 2,
			  nav: true,
			  autoplayHoverPause: true,
			  animateOut: 'slideOutUp',
			  animateIn: 'slideInUp'
		  });
		});
</script>
<?php } ?>
